application:
  classes:
    HackLabController: /
    UserController: /user
  image-dir: media/img
  path: hacklab/controllers.py
  static:
    /media: media
  template-dir: templates
  boot:
    path: hacklab/startup.py
    callable: startup
autoreload: true
host: 0.0.0.0
port: 4000
run-as: wsgi
extra:
  database-engine: sqlite:///database_hacklab.sqlite
  repositories-dir: ./repositories
